package com.example.am_store;

import javafx.collections.ObservableList;

public class orderdetails {
    private int orderDetailsId;
    private int orderId;
    private int productId;
    private int quantity;
    private double price; // Changed to double to handle price more accurately
    private String nameProduct;

    // Constructor to initialize the order details
    public orderdetails(int orderId, int productId, int quantity, double price, String nameProduct, double v) {
        this.orderDetailsId = 0; // Assuming ID is auto-generated by DB
        this.orderId = orderId;
        this.productId = productId;
        this.quantity = quantity;
        this.price = price;
        this.nameProduct = nameProduct;
    }

    public orderdetails(int orderDetailsId, String productName, int productId, int quantity, double price) {
        this.orderDetailsId = 0; // Assuming ID is auto-generated by DB
        this.orderId = orderId;
        this.productId = productId;
        this.quantity = quantity;
        this.price = price;
        this.nameProduct = nameProduct;
    }

    public orderdetails(String productName, int productId, int quantity, double price) {
        this.productId = productId;
        this.quantity = quantity;
        this.price = price;
        this.nameProduct= nameProduct;
    }


    // Getters and setters
    public int getOrderDetailsId() { return orderDetailsId; }
    public void setOrderDetailsId(int orderDetailsId) { this.orderDetailsId = orderDetailsId; }

    public int getOrderId() { return orderId; }
    public void setOrderId(int orderId) { this.orderId = orderId; }

    public int getProductId() { return productId; }
    public void setProductId(int productId) { this.productId = productId; }

    public int getQuantity() { return quantity; }
    public void setQuantity(int quantity) { this.quantity = quantity; }

    public double getPrice() { return price; }  // Use double for price to support decimal values
    public void setPrice(double price) { this.price = price; }

    public String getNameProduct() { return nameProduct; }
    public void setNameProduct(String nameProduct) { this.nameProduct = nameProduct; }
}
